# 测试使用的证券番号
#"001": "68501058548"
#"002": "76780040372"
#"003": "76780040372"


# 火灾
"101":
        role:      "火災ユーザー1"
        branch:    "火災"
        node:      "点検1回目"
"102":
        role:      "火災ユーザー1"
        branch:    "火災"
        node:      "点検2回目"
"103":
        role:      "火災ユーザー1"
        branch:    "火災"
        node:      "返金解約点検"
"104":
        role:      "火災ユーザー1"
        branch:    "火災"
        node:      "不備案件"
"105":
        role:      "火災ユーザー1"
        branch:    "火災"
        node:      "オンライン計上"
"106":
        role:      "火災ユーザー1"
        branch:    "火災"
        node:      "web计上"
"107":
        role:      "火災ユーザー1"
        branch:    "火災"
        node:      "リビングアシスト計上"
"108":
        role:      "火災ユーザー1"
        branch:    "火災"
        node:      "バッチ計上準備"
"109":
        role:      "火災ユーザー1"
        branch:    "火災"
        node:      "バッチエラー待"
"110":
        role:      "火災ユーザー1"
        branch:    "火災"
        node:      "付箋不備"
"111":
        role:      "火災ユーザー1"
        branch:    "火災"
        node:      "エラー待"
"112":
        role:      "火災ユーザー1"
        branch:    "火災"
        node:      "エラー修正"
"113":
        role:      "火災ユーザー1"
        branch:    "火災"
        node:      "計上確認"
"114":
        role:      "火災ユーザー1"
        branch:    "火災"
        node:      "問合せ"
"115":
        role:      "火災ユーザー1"
        branch:    "火災"
        node:      "問合せ回答"
"116":
        role:      "火災ユーザー1"
        branch:    "火災"
        node:      "不明書類"